CREATE TABLE PT_SRV_USAGE
(
  SRV_IP                VARCHAR2(30 CHAR)       NOT NULL,
  SRV_TYPE              VARCHAR2(30 CHAR),
  SRV_MEM_USAGE         FLOAT(126),
  SRV_DISK_USAGE_ROOT   FLOAT(126),
  SRV_DISK_USAGE_PART1  FLOAT(126),
  SRV_DISK_USAGE_PART2  FLOAT(126),
  SRV_CPU_LOAD          FLOAT(126),
  PROJECT               VARCHAR2(30 CHAR),
  SRV_HOSTNAME          VARCHAR2(30 CHAR),
  SRV_PT_TOMCAT_STATUS  VARCHAR2(30 CHAR),
  SRV_BK_STATUS         VARCHAR2(30 CHAR)
);